config/routes.rb
Rails.application.routes.draw do
  resources :time_records do
    collection do
      get  :advanced_search
      post :filter
      get  :redraw
      get  :versions
    end
  end
end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
  MAX_MINUTES_ELAPSED = 10 * 60

  belongs_to :user

  belongs_to :project
  belongs_to :assignee, class_name: 'User', foreign_key: :assigned_to

  has_one :time_record_account, :dependent => :destroy
  has_one :account, :through => :time_record_account

  has_many :emails, :as => :mediator
  serialize :subscribed_users, Set

  uses_user_permissions
  acts_as_commentable
  has_paper_trail
  exportable

  sortable :by => ["rate DESC", "minutes_elapsed DESC", "created_at DESC", "updated_at DESC" ], :default => "created_at DESC"

  has_ransackable_associations %w(user assignee account project activities)

  before_save :update_rate

  validates :date_started, presence: true
  validates :category, :inclusion => { :in => Proc.new { Setting.unroll(:time_tracking_rate_names).map { |s| s.last.to_s } } }
  validates :minutes_elapsed, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: MAX_MINUTES_ELAPSED }, if: :time_spent_valid?
  validates_numericality_of :rate, :allow_nil => true

  validate :validate_time_spent

  # Time Record created by the user for herself, or assigned to her by others.
  scope :my, ->(*args) {
    options = args[0] || {}
    user_option = (options.is_a?(Hash) ? options[:user] : options) || User.current_user
    includes(:assignee).
        where('(user_id = ? AND assigned_to IS NULL) OR assigned_to = ?', user_option, user_option).
        order(options[:order] || 'created_at ASC').
        limit(options[:limit]) # nil selects all records
  }

  # Search by name OR id
  scope :text_search, ->(query) {
    search('description_or_target_or_project_name_or_account_name_or_assignee_first_name_or_assignee_last_name_cont' => query).result
  }

  scope :created_by,  ->(user) { where(user_id: user.id ) }
  scope :assigned_to, ->(user) { where(assigned_to: user.id ) }

  # Time Record assigned by the user to others. That's what we see on TimeRecord/Assigned.
  scope :assigned_by, ->(user) {
    includes(:assignee).
      where('user_id = ? AND assigned_to IS NOT NULL AND assigned_to != ?', user.id, user.id)
  }

  # Time Record created by the user or assigned to the user, i.e. the union of the two
  # scopes above. That's the tasks the user is allowed to see and track.
  scope :tracked_by, ->(user) {
    includes(:assignee).
        where('user_id = ? OR assigned_to = ?', user.id, user.id)
  }

  def time_spent
    @time_spent ||= begin
      (minutes_elapsed / 60.0).round(2)
    rescue
      ''
    end
  end

  def time_spent=(value)
    @time_spent = begin
      timespan = Timespan.new("#{Float(value.to_s)} hrs")
      self.minutes_elapsed = timespan.to_minutes
      value.to_s
    rescue
      ''
    end
  end

  def save_with_account(params)
    params[:account].delete(:id) if params[:account][:id].blank?
    account = Account.create_or_select_for(self, params[:account])
    self.time_record_account = TimeRecordAccount.new(:account => account, :time_record => self) unless account.id.blank?
    self.account = account
    result = self.save
    result
  end

  def update_with_account(params)
    if params[:account] && (params[:account][:id] == "" || params[:account][:name] == "")
      self.account = nil
    elsif params[:account]
      account = Account.create_or_select_for(self, params[:account])
      if self.account != account and account.id.present?
        self.time_record_account = TimeRecordAccount.new(:account => account, :time_record => self)
      end
    end
    self.reload
    self.attributes = params[:time_record]
    self.save
  end

  protected

  def update_rate
    self.rate = Setting[:time_tracking_rates][self.category]
  end

  def validate_time_spent
    errors.add(:time_spent, I18n.t(:blank, scope: [:activerecord, :errors, :messages])) unless time_spent_valid?
  end

  def time_spent_valid?
    !(time_spent.nil? || time_spent.strip == '')
  end

end

app/controllers/time_records_controller.rb
class TimeRecordsController < EntitiesController
  before_filter :load_settings
  before_filter :set_params, :only => [ :index, :redraw, :filter ]

  # GET /time_records
  #----------------------------------------------------------------------------
  def index
    @time_records = get_time_records(:page => params[:page])

    respond_with @time_records do |format|
      format.xls { render :layout => 'header' }
      format.csv { render :csv => @time_records }
    end
  end

  # GET /time_records/new
  #----------------------------------------------------------------------------
  def new
    @time_record.attributes = {:user => current_user, :assigned_to => current_user, :date_started => Date.current}
    @account  = Account.new(:user => current_user, :access => Setting.default_access)
    @accounts = Account.my.order('name')

    if params[:related]
      model, id = params[:related].split('_')
      if related = model.classify.constantize.my.find_by_id(id)
        instance_variable_set("@#{model}", related)
      else
        respond_to_related_not_found(model) and return
      end
    end

    if @project && @project.account
      @account = @project.account
    end

    respond_with(@time_record)
  end

  # GET /time_records/1/edit                                                      AJAX
  #----------------------------------------------------------------------------
  def edit
    @time_record = TimeRecord.tracked_by(current_user).find(params[:id])
    @account   = @time_record.account || Account.new(:user => current_user)
    @accounts  = Account.my.order('name')

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = TimeRecord.my.find_by_id($1) || $1.to_i
    end

    respond_with(@time_record)
  end

  # POST /time_records
  #----------------------------------------------------------------------------
  def create
    respond_with(@time_record) do |format|
      unless @time_record.save_with_account(params)
        @accounts = Account.my.order('name')
        unless params[:account][:id].blank?
          @account = Account.find(params[:account][:id])
        else
          if request.referer =~ /\/accounts\/(\d+)\z/
            @account = Account.find($1) # related account
          else
            @account = Account.new(:user => current_user)
          end
        end
      end
    end
  end

  # PUT /time_records/1
  #----------------------------------------------------------------------------
  def update
    respond_with(@time_record) do |format|
      unless @time_record.update_with_account(params)
        @accounts = Account.my.order('name')
        if @time_record.account
          @account = Account.find(@time_record.account.id)
        else
          @account = Account.new(:user => current_user)
        end
      end
    end
  end

  # DELETE /time_records/1
  #----------------------------------------------------------------------------
  def destroy
    @time_record.destroy

    respond_with(@time_record) do |format|
      format.html { respond_to_destroy(:html) }
      format.js   { respond_to_destroy(:ajax) }
    end
  end

  # GET /time_records/redraw                                                      AJAX
  #----------------------------------------------------------------------------
  def redraw
    current_user.pref[:time_records_per_page] = params[:per_page] if params[:per_page]

    # Sorting and naming only: set the same option for Contacts if the hasn't been set yet.
    if params[:sort_by]
      current_user.pref[:time_records_sort_by] = TimeRecord::sort_by_map[params[:sort_by]]
    end

    if params[:naming]
      current_user.pref[:time_records_naming] = params[:naming]
    end

    @time_records = get_time_records(:page => 1, :per_page => params[:per_page]) # Start one the first page.
    set_options # Refresh options

    respond_with(@time_records) do |format|
      format.js { render :index }
    end
  end

  # POST /time_records/filter                                                     AJAX
  #----------------------------------------------------------------------------
  def filter
    session[:time_records_filter] = params[:status]
    @time_records = get_time_records(:page => 1, :per_page => params[:per_page]) # Start one the first page.

    respond_with(@time_records) do |format|
      format.js { render :index }
    end
  end

  private

  alias :get_time_records :get_list_of_records

  def set_params
    current_user.pref[:time_records_per_page] = params[:per_page] if params[:per_page]
    current_user.pref[:time_records_sort_by]  = TimeRecord::sort_by_map[params[:sort_by]] if params[:sort_by]
  end

  def load_settings
    @category = Setting.unroll(:time_tracking_rate_names)
  end

  #----------------------------------------------------------------------------
  def respond_to_destroy(method)
    if method == :ajax
      if called_from_index_page?                  # Called from Leads index.
        @time_records = get_time_records          # Get time_records for current page.
        if @time_records.blank?                   # If no time_record on this page then try the previous one.
          @time_records = get_time_records(:page => current_page - 1) if current_page > 1
          render :index and return                # And reload the whole list even if it's empty.
        end
      else                                        # Called from related asset.
        self.current_page = 1                     # Reset current page to 1 to make sure it stays valid.
      end                                         # Render destroy.js
    else # :html destroy
      self.current_page = 1
      flash[:notice] = t(:msg_asset_deleted, 'time record')
      redirect_to time_records_path
    end
  end
end

app/helpers/time_records_helper.rb
module TimeRecordsHelper
  include UsersHelper

  def user_select_for_current_user(asset, users, myself)
    user_options = user_options_for_select(users, myself)
    select(asset, :assigned_to, user_options,
           { :include_blank => t(:unassigned), :selected => myself.id },
           { :style         => "width:160px",
             :class => 'select2'              })
  end

  def time_record_project_select(options = {})
    options[:selected] ||= @time_record.project_id || (@project && @project.id) || 0
    selected_projects = Project.my.where(id: options[:selected]).to_a
    projects = selected_projects# (selected_projects + Project.my.limit(25)).compact.uniq

    select_tag('time_record[project_id]', options_from_collection_for_select(projects, :id, :name, options),
      { :"data-placeholder" => t(:select_a_project), :"data-url" => auto_complete_projects_path(format: 'json'),
        style: "width:155px; display:none;", class: 'ajax_chosen_1', include_blank: t(:no_project_assigned) })
  end

  def section_without_select(related, assets)
    asset = assets.to_s.singularize
    create_id  = "create_#{asset}"
    create_url = controller.send(:"new_#{asset}_path")

    html = tag(:br)
    html << content_tag(:div, link_to_inline(create_id, create_url, :related => dom_id(related), :text => t(create_id)), :class => "subtitle_tools")
    html << content_tag(:div, t(assets), :class => :subtitle, :id => "create_#{asset}_title")
    html << content_tag(:div, "", :class => :remote, :id => create_id, :style => "display:none;")
  end
end

app/views/time_records/_edit.html.haml
.remote
  = form_for(@time_record, :html => one_submit_only.merge({:autocomplete => 'off'}), :method => :put, :remote => true) do |f|
    = link_to_close edit_time_record_path(@time_record)

    = f.error_messages :object_name => t('time_record')
    = render "time_records/form", :f => f, :edit => true

    .buttonbar
      = f.submit t(:save_time_record)
      #{t :or}
      = link_to_cancel edit_time_record_path(@time_record)

app/views/time_records/_form.html.haml
= hook(:time_tracking_top_section, self, :f => f) do
  .section
    = fields_for(@account) do |a|
      = a.hidden_field :user_id
      = a.hidden_field :assigned_to
      %table
        %tr
          %td{colspan: 2}
            = account_select_or_create(a) do |options|
              - options[:selected] = @account.id || 0
              - options[:include_blank] = true
        %tr
          %td{style: "width: 170px"}
            .label #{t :assign_to}:
            = user_select_for_current_user(:time_record, all_users, current_user)
          %td
            .label #{t :project}:
            = time_record_project_select
        %tr
          %td{style: "width: 170px"}
            .label.req #{t :rate_category}:
            = f.select :category, @category, { :selected => @time_record.category.blank? ? nil : @time_record.category.to_sym }, { :style => "width:160px" }
          %td
            .label #{t :target}:
            = f.text_field :target, rows: 5, style: 'width: 150px'
        %tr
          %td
            .label.req #{t :date_started}:
            = f.text_field :date_started, :style => "width:150px;", :autocomplete => :off, :class => 'date'
          %td
            .label.req #{t :time_spent}:
            = f.text_field :time_spent, { :style => "width:150px" }
        %tr
          %td{colspan: 2}
            .label #{t :description}:
            = f.text_area :description, rows: 5, style: 'width: 320px'

        = hook(:time_tracking_top_section_bottom, self, :f => f)

app/views/time_records/_list.html.haml
= section_without_select(object, :time_records)

.list#time_records
  - time_records = object.time_records.order('updated_at desc').paginate(:page => 1, :per_page => 20)
  = render :partial => "time_records/time_record", :collection => time_records

= paginate( collection: time_records, id: 'time_records_pagination', params: { action: 'time_records' } )

app/views/time_records/_new.html.haml
= form_for(@time_record, :html => one_submit_only.merge({:autocomplete => 'off'}), :remote => true) do |f|
  = link_to_close new_time_record_path

  = f.error_messages :object_name => t('time_record')
  = render "time_records/form", :f => f

  .buttonbar
    = f.submit t(:create_time_record)
    #{t :or}
    = link_to_cancel new_time_record_path

app/views/time_records/_time_record.html.haml
%li.highlight[time_record]
  .strip{:class => time_record.category }= t(time_record.category)

  %ul.tools
    - params[:klass_name] = 'time_record'
    %li= link_to_edit time_record
    %li= link_to_delete time_record

  .indent
    == #{t :reported}: #{pluralize(time_record.time_spent, 'hour')}
    - if (project = time_record.project) && project.id
      == #{' | '} #{t :project}: #{link_to_if can?(:read, project), project.name, project_path(project)}
    - if (account = time_record.account) && account.id
      == #{' | '} #{t :account}: #{link_to_if can?(:read, account), account.name, account_path(account)}
    - if (assignee = time_record.assignee) && assignee.id
      == #{' | '} #{t :assignee}: #{link_to_if can?(:read, assignee), assignee.full_name, admin_user_path(assignee)}
    %tt
      &ndash;
      - user_name = time_record.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => timeago(time_record.created_at), :user => h(user_name)).html_safe
      - else
        = t(:added_ago, :value => timeago(time_record.created_at)).html_safe
    %dt
      %b #{t(:description)}:
      = time_record.description.blank? ? t(:no_description) : time_record.description

app/views/time_records/_title_bar.html.haml
#confirm{ hidden }
.title_tools#menu
  = link_to_function(t(:delete) + '?', confirm_delete(@time_record))
.title_tools#buttons
  = view_buttons
.title#edit_time_record_title
  = h(t(:time_record))
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

%div#edit_time_record{ hidden }

app/views/time_records/create.js.haml
- if @time_record.persisted?
  - id = dom_id(@time_record)

  $('#create_time_record_arrow').html(crm.COLLAPSED);
  $('#create_time_record_title').html('#{ j t(:time_records) }');
  $('#create_time_record').slideUp(250);
  $('#time_records').prepend('#{ j (render :partial => "time_record", :collection => [ @time_record ]) }');
  $('##{id}').effect("highlight", { duration:1500 });
- else
  $('#create_time_record').html('#{ j render(:partial => "new") }');
  $('#create_time_record').effect("shake", { duration:250, distance: 6 });
  $('#time_record_name').focus();

app/views/time_records/destroy.js.haml
- id = dom_id(@time_record)
$('##{id}').css('background-color', '#ffe4e1').slideUp(250);

app/views/time_records/edit.js.haml
- id = dom_id(@time_record)

- if params[:cancel].true?
  $('##{id}').replaceWith('#{ j (render(:partial => "time_record", :collection => [ @time_record ])) }');
- else
  crm.highlight_off('#{id}');
  crm.hide_form('create_time_record');
  $('##{id}').html('#{ j render(:partial => "edit") }');
  $('#time_record_name').focus();

app/views/time_records/index.html.haml
= styles_for :time_record

.title_tools
  = link_to_inline(:create_time_record, new_time_record_path, :text => t(:create_time_record))

.title
  %span#create_time_record_title #{t :time_records}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

.remote#create_time_record{ hidden }

= render 'search'

%ul.list#time_records
  - if @time_records.length > 0
    = render :partial => "time_record", :collection => @time_records
  - else
    = render "shared/empty"

#paginate= render "shared/paginate_with_per_page"
#export= render "shared/export"

app/views/time_records/index.js.haml
- if @time_records.length > 0
  $('#time_records').html('#{ j render(:partial => "time_records/time_record", :collection => @time_records) }');
- else
  $('#time_records').html('#{ j render(:partial => "shared/empty") }');

$('#paginate').html('#{ j render(:partial => "shared/paginate_with_per_page") }');
$('#export').html('#{ j render(:partial => "shared/export") }');

app/views/time_records/new.js.haml
crm.flip_form('create_time_record');

- unless params[:cancel].true?
  $('#create_time_record').html('#{ j render(:partial => "new") }');
  $('#empty').html('');
  crm.set_title('create_time_record', '#{t(:create_time_record)}');
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
- else
  crm.set_title('create_time_record', '#{t(:time_records)}');

app/views/time_records/show.html.haml
- if (template = template_for_current_view)
  = render(template, :time_record => @time_record)
- else
  = render 'time_records/title_bar', :time_record => @time_record

  = render "comments/new", :commentable => @time_record
  = render :partial => "shared/timeline", :collection => @timeline

  = hook(:show_time_record_bottom, self) do

    = render "versions/versions", :object => @time_record

app/views/time_records/update.js.haml
- id = dom_id(@time_record)

- if @time_record.errors.empty?
  $('##{id}').replaceWith('#{ j render(:partial => "time_record", :collection => [ @time_record ]) }')
  $('##{id}').effect("highlight", { duration:1000 });
- else
  $('##{id}').html('#{j render(:partial => "edit") }')
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('#time_record_name').focus()